[package]
name = "sqlparser"
version = "0.1.0"
edition = "2021"
authors = ["Alice Carra <aalicecarra@gmail.com>"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_derive = "1.0"

nom = "7.1"
